internal/webserver/webserver.go
Closes #28.
Please, @bsctl try this release pushed on Quay.io as `quay.io/clastix/capsule-ns-filter:v0.0.4-rc0`
=> Closing response handler to avoid memory leak

charts/capsule-proxy/templates/_helpers.tpl, charts/capsule-proxy/templates/deployment.yaml
The image tag defaults to `appVersion` which is currently `0.0.5`. However, the image is actually tagged `v0.0.5`.
=> correct default image tag to match published image

README.md, internal/options/kube.go, internal/options/listener.go, internal/webserver/webserver.go, main.go
This PR Closes #67 and allow the connection to kubernetes using kubectl files.
1. `k8s-control-plane-url` cmd option is Deprecated, now k8s api endpoint is obtained by kubeconfig, 
2. Authentication to k8s is done using certificates from kubeconfig. 
3. If running out of cluster you should provide the kubeconfig file using `--kubeconfig` cmd option!
```bash
go run main.go --ssl-cert-path=/tmp/localhost.pem --ssl-key-path=/tmp/localhost-key.pem  --kubeconfig=./config.kub --enable-ssl=true
```
I've manually tested with kind and I'm able to get nemespaces kubernetes api both out of cluster and in cluster.
In cluster it is using the TLS configuration provided by kubernetes automatically!
@prometherion when tests are ready we should run this against automated tests before merging.
@MaxFedotov …
=> Using kubeconfig to access the kubernetes api

Makefile, e2e/run.bash, e2e/tests/00_namespaces_list.bats, e2e/tests/01_namespaces_filtering.bats, e2e/tests/02_node_listing.bats, e2e/tests/03_root.bats, e2e/tests/04_namespace_managing.bats
Partially addressing #64, with `kubectl` we should have fewer headaches since there is a built-in retry method and output management that helps the assertions.
=> e2e test using kubectl

Dockerfile, go.mod
=> Upgrading the Docker build target to Go 1.16

e2e/tests/05_denied_namespaces.bats, internal/webserver/webserver.go
Closes #74, and closes #65 as well.
Along with the additional test case checking for the expected failure due to missing RoleBinding for the _default_ namespace, this refactoring solves the out-of-cluster mode, as well implementing the middleware logic that skips User-Authentication for the decorated requests (`/api/v1/namespaces` and `/api/v1/nodes`).
A prerequisite to solving #74 was implementing #65, although already assigned to @ludusrusso: having a review from you would be great, as well co-authoring the commits.
=> Switching over middleware to solve out-of-cluster mode

Makefile, e2e/run.bash, e2e/tests/06_node_get.bats, internal/request/http.go, internal/request/request.go
Hi @prometherion, 
Thanks a lot for your work :)
When I've tried to run `make e2e` on OS X found an issue with mkcert rootCA location - it is different then on Linux, so I've fixed it.
Also I've added tests for cordon\taint (although they are just the same editing node spec, but in case something changes in future I think it is a good idea to have them)
And I removed unused interface methods from request
=> Makefile support OS X. Additional tests for node. Remove unused request interfaces

README.md
=> docs: k8s-control-plane-url CLI flag is deprecated

internal/webserver/webserver.go
The kubernetes documentation specifies group information is set in multiple headers, not a single header with comma separation. https://kubernetes.io/docs/reference/access-authn-authz/authentication/#user-impersonation
This change replaces the string.Join with a simple loop over the groups to implement this change.
=> Use multiple Impersonate-Group headers

charts/capsule-proxy/Chart.yaml, charts/capsule-proxy/README.md, charts/capsule-proxy/templates/daemonset.yaml, charts/capsule-proxy/templates/deployment.yaml, charts/capsule-proxy/values.yaml, go.mod, go.sum, internal/options/kube.go, internal/options/listener.go, internal/webserver/middleware/user_in_group.go, internal/webserver/webserver.go, main.go
Closes #119.
Adding a new slice CLI flag named `--ignored-user-group` an administrator can set which groups must be ignored from filtering, executing just the impersonate handler and bypassing all the underlying handlers.
=> Ignoring certain user groups from filtering

charts/capsule-proxy/README.md, charts/capsule-proxy/templates/daemonset.yaml, charts/capsule-proxy/templates/deployment.yaml, charts/capsule-proxy/values.yaml, internal/controllers/capsule_configuration.go, internal/options/kube.go, internal/options/listener.go, internal/webserver/middleware/user_in_group.go, internal/webserver/webserver.go, main.go
Closes #144.
The old flag `--capsule-user-group` will be still available to preserve backward compatibility, will be removed in the next minor release.
Args passed by `--capsule-user-group` CLI flag will have precedence over `--capsule-configuration-name`.
=> Reading CapsuleConfiguration CR for Capsule user groups retrieval.

README.md
No kubeconfig flag is available. Let's use `KUBECONFIG` env variable instead.
=> docs: no kubeconfig flag

charts/capsule-proxy/Chart.yaml
Tagging on GitHub after merging this PR that will fail.
=> Releasing capsule-proxy v0.2.0

charts/capsule-proxy/Chart.yaml, charts/capsule-proxy/templates/ingress.yaml
Failed to deploy on k8s v1.22 before this change.
As per https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.22/#httpingresspath-v1-networking-k8s-io
Capsule is great, thank you! :)
=> fix: ingress service reference in networking.k8s.io/v1

Dockerfile, Makefile, go.mod, internal/webserver/webserver.go
Closes #188.
We strongly suggest upgrading ASAP `capsule-proxy` to mitigate this CVE that doesn't have direct mitigation.
=> bug: cve exploiting malicious connection header

internal/webserver/middleware/authorization.go, internal/webserver/middleware/authorization_test.go
Issue: the regex pattern for the checkBearerToken function currently does not support webtokens.
Solution: This PR added makes it so that both webtokens and jwts pass the regex
Reference https://github.com/clastix/capsule-proxy/issues/194
=> Fix webtoken auth

charts/capsule-proxy/Chart.yaml, charts/capsule-proxy/README.md, charts/capsule-proxy/templates/certgen-job.yaml
This PR fixes #211 by including the certificate generation Job to the Helm chart resources, from [post-install hooks](https://helm.sh/docs/topics/charts_hooks/#hooks-and-the-release-lifecycle).
Signed-off-by: Massimiliano Giovagnoli <me@maxgio.it>
=> deploy(charts): move certgen job to chart resources

internal/request/error.go, internal/request/http.go, internal/webserver/webserver.go
This PR adds a specific error type return and management when the user and groups that are wanted to be impersonated can't be due to missing privileges.
=> Handle GetUserAndGroups() failure for missing privileges

internal/webserver/middleware/metrics.go
Fixes #224.
@viveksyngh please, take a look: I was able to exec in a Pod and getting metrics populated properly.
```
KUBECONFIG=alice-solar.capsule kubectl -n solar-development exec -it nginx-798bbb699b-rxfrk bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl exec [POD] -- [COMMAND] instead.
nginx@nginx-798bbb699b-rxfrk:/$ echo 1
1
nginx@nginx-798bbb699b-rxfrk:/$ 
exit
```
```
curl -s localhost:8080/metrics | grep -i capsule_proxy
capsule_proxy_requests_total{path="/",status="200"} 36
capsule_proxy_response_time_seconds_bucket{path="/",le="0.005"} 1
capsule_proxy_response_time_seconds_bucket{path="/",le="0.01"} 1
capsule_proxy_response_time_seconds_bucket{path="/",le="0.025"} 1
capsule_proxy_response_time_seconds_bucket{path="/",le="0.05"} …
```
=> fix: implementing hijack interface for metrics middleware

go.mod, go.sum, internal/request/http.go
Closes #232.
With these changes, we're going to offload processing of authentication tokens to the [`TokenReview` API](https://kubernetes.io/docs/reference/kubernetes-api/authentication-resources/token-review-v1/). We're not expecting any performance degradation since, according to the documentation:
> TokenReview requests may be cached by the webhook token authenticator plugin in the kube-apiserver
=> fix: delegating user and group validation to tokenreview api

charts/capsule-proxy/README.md, charts/capsule-proxy/templates/ingress.yaml, charts/capsule-proxy/values.yaml
The ingress class annotation (e.g. `kubernetes.io/ingress.class: nginx`) has been deprecated since Kubernetes 1.18. This change adds support for setting `ingress.className` in the chart values which in turn sets the `spec.ingressClassName` field on the Ingress object for Capsule Proxy. `ingress.className` should refer to an existing `IngressClass` object. Note, the annotation and `ingressClassName` field cannot be used together or you'll get an error from the Kubernetes API.
=> feat: support ingressclassname in chart

charts/capsule-proxy/Chart.yaml, charts/capsule-proxy/README.md, charts/capsule-proxy/ci/deploy-values.yaml, charts/capsule-proxy/ci/ds-values.yaml, charts/capsule-proxy/templates/_helpers.tpl, charts/capsule-proxy/templates/certmanager.yaml, charts/capsule-proxy/values.yaml
Currently in [certmanager.yaml](https://github.com/clastix/capsule-proxy/blob/master/charts/capsule-proxy/templates/certmanager.yaml) following use cases are supported:
- Generate self-signed certificates for capsule-proxy using the self-signed issuer
- Generate the ca signed certificates for capsule-proxy using the ca-issuer
With this pull request I am adding support for one more use case details of which are as follows:
- I have a ClusterIssuer in the K8s cluster which is used by all the apps in the cluster for Certificate generation
- For capsule-proxy instead of using self signed issuer or ca issuer I want to use ClusterIssuer to generate capsule-proxy-serving-cert.
I refactored  [certmanager.yaml](https://github.com/clastix/capsule-proxy/blob/master/charts/capsule-proxy/templates/cert …
=> feat: support for clusterissuer in chart

charts/capsule-proxy/Chart.yaml, charts/capsule-proxy/README.md, charts/capsule-proxy/templates/_helpers.tpl, charts/capsule-proxy/templates/certmanager.yaml, charts/capsule-proxy/values.yaml
This PR adds the Kubernetes `Service` DNS names to the DNS SANs of the Cert Manager generated `Certificate`.
Moreover, it removes the host name of the main `Ingress` rule when the ingress is disabled.
Finally, removes ambiguity in the variable names and adds documenting comments.
Fixes #262
=> Set correct SANs when using cert-manager

internal/request/http.go
If you are not authenticated, don't return the `capsule` name in the error message. This helps reduce information leaking to anonymous requests.
=> fix: do not expose service name to anonymous requests

internal/webserver/webserver.go
* If `TLSCertAuth` is not provided as one of the preferred auth types then skip verification
closes #271
=> only verify client cert if TLSCertAuth is active

charts/capsule-proxy/Chart.yaml, charts/capsule-proxy/README.md, charts/capsule-proxy/templates/_pod.tpl, charts/capsule-proxy/values.yaml
This PR introduces `authPreferredTypes` option in helm variables, that allows to configure `--auth-preferred-types` parameter in Capsule Proxy.
=> chore(helm): Allow to specify authPreferredTypes

Makefile
Fixes https://github.com/clastix/capsule-proxy/issues/285
=> fix: error: got secret, but it did not contain a 'ca' key (#285)

charts/capsule-proxy/Chart.yaml, charts/capsule-proxy/templates/certgen-job.yaml
The certgen-job did not respected the fullnameoverride.
Unified the labels with other resource labels in this process.
=> Fix fullnameoverride certgen job

.github/workflows/ci.yaml, Dockerfile, go.mod
update golang to 1.19 to allow for easier recompile using boringcrypto added to main in 1.19. Also moved from alpine to just regular golang to standardize between capsule and capsule-proxy.
=> fix: update golang to 1.19

charts/capsule-proxy/Chart.yaml, charts/capsule-proxy/templates/certgen-job.yaml
imagePullSecrets were misplaced under containers instead directly under spec. This PR will fix this.
=> fix: imagePullSecrets belongs to spec instead of containers

charts/capsule-proxy/Chart.yaml, charts/capsule-proxy/templates/_pod.tpl
This is to add client side rate limiters in the helm manifests
Changes with code are already merged in the following PR's and released with v0.4.4.
https://github.com/clastix/capsule-proxy/pull/300
https://github.com/clastix/capsule-proxy/pull/301
=> fix(helm): add client side rate limiters

internal/request/impersonation.go
Closes #305.
@msergg may I ask you to give a try to these changes to your environment? Unfortunately, I don't have an Active Directory backed environment: you need to build on your own and push to a container registry.
https://github.com/clastix/capsule-proxy/blob/193bdab39373d0dfa470ae09956dbb38f25bb069/Makefile#L20-L22
=> fix: retrieving groups from header values

charts/capsule-proxy/Chart.yaml, charts/capsule-proxy/README.md, charts/capsule-proxy/templates/certgen-job.yaml, charts/capsule-proxy/values.yaml
This is needed if capsule-proxy is rolled out with ArgoCD, see: https://argo-cd.readthedocs.io/en/stable/user-guide/resource_hooks/#hook-deletion-policies
=> feat(helm): add annotations for certgen job and make ttlSecondsAfterFinished optional

.github/workflows/e2e.yaml
Related to #257:
> The current e2e is unusable, too flaky, and unreliable
=> chore(e2e): disabling flaky e2e, needs refactoring

internal/options/kube.go, internal/options/listener.go, internal/request/http.go, internal/request/http_test.go, internal/request/impersonation.go, internal/webserver/middleware/user_in_group.go, internal/webserver/webserver.go, main.go
Adds options to filter groups that will be impersonated. We experienced based on the correction in (https://github.com/projectcapsule/capsule-proxy/pull/331) that the performance greatly decreased because of the amount of groups we have in the claim and the resulting requests to the API server.
With these options the amount of groups which are considered for impersonated can be decreased resulting in less requests.
@MaxFedotov wdyt? Do you also experience performance issues? did you also change the qos and burst of the kube client?
Maybe we can do additional adjustments to improve the performance. But i can't think of anything else to decrease the requests made to the API to request impersonation.  Batching all the groups would help, however there's nothing on the kubernetes API which …
=> feat(controller): add impersonation group filter options

charts/capsule-proxy/Chart.yaml, charts/capsule-proxy/README.md, charts/capsule-proxy/templates/_pod.tpl, charts/capsule-proxy/values.yaml
=> fix(helm): add support for extraargs

internal/request/http.go, internal/request/http_test.go
Fixes service account impresonation regression discussed in https://github.com/projectcapsule/capsule-proxy/issues/388#issuecomment-1970791462.
=> fix: impresonation regression for service accounts

main.go
Fixes #390
If I understand correctly, the client needs to swaped. since `GetClient()`:
```
// GetClient returns a client configured with the Config. This client may
// not be a fully "direct" client -- it may read from a cache, for
// instance.  See Options.NewClient for more information on how the default
// implementation works.
```
=> fix(controller): correct client overwrites

charts/capsule-proxy/README.md, charts/capsule-proxy/templates/_pod.tpl, charts/capsule-proxy/values.yaml
=> feat(chart): additional deployment object configurations

internal/webserver/middleware/jwt.go
=> fix: lru cache for invalidated tokens

charts/capsule-proxy/templates/certmanager.yaml
=> fix: allow wildcards on certificate generation

go.mod, go.sum, internal/options/kube.go, internal/options/listener.go, internal/webserver/webserver.go
Fixes #566 
From kubernetes 1.30 kubelet takes care of renewing tokens for service accounts inside the projected volumes. This PR make capsule-proxy to reload the token when required.
=> fix: support service account bound token expiration

internal/request/http.go, internal/request/http_test.go
This is a simple change that enables us to extract the JWT from the WebSocket protocols as defined here https://github.com/kubernetes/kubernetes/pull/47740. This satisfies #499.
Let me know if any changes are needed.
Thank you!
=> feat: add support for bearer tokens in websocket protocols

charts/capsule-proxy/Chart.yaml
When publishing a Capsule Proxy release, Chart and Image versions are inflected automatically from the git tag: having fixed values in the Helm Chart is useless.
https://github.com/projectcapsule/capsule-proxy/blob/b2097d56dc8f03b727447280986c4df1a58b5cab/.github/workflows/helm-publish.yml#L62-L63
=> chore(helm): removing hard coded version values

charts/capsule-proxy/README.md, charts/capsule-proxy/templates/certgen-job.yaml, charts/capsule-proxy/values.yaml
Closes https://github.com/projectcapsule/capsule-proxy/issues/594
=> feat: add resources to capsule-proxy-certgen helm job

Makefile, charts/capsule-proxy/README.md, charts/capsule-proxy/README.md.gotmpl, charts/capsule-proxy/ci/webhook-values.yaml, charts/capsule-proxy/templates/_helpers.tpl, charts/capsule-proxy/templates/_pod.tpl, charts/capsule-proxy/templates/webhooks/certificate.yaml, charts/capsule-proxy/templates/webhooks/mutating.yaml, charts/capsule-proxy/templates/webhooks/service.yaml, charts/capsule-proxy/values.yaml, internal/controllers/watchdog/namespaced_watcher.go, internal/webhooks/watchdog.go, main.go
We have some changes here:
- `pprof` should not be available always, only if specified via args. This is to prevent any leakage in production environments.
- `Watchdog`: only reconcile for `CREATE` and `UPDATE`, everything else does not matter for the labels
- `Webhooks`: Add Webhooks to the proxy. The watchdog webhook is very primitive. We have left a lot of configuration options for the webhook in the `values.yaml`. The webhooks are not enabled by default and the watchdog webhook is a failurePolicy of ignore by default. Updating should therefor not cause any interruptions
Using this Webhook will also resolve #530
=> feat: proxy webhooks

.github/configs/lintconf.yaml, .pre-commit-config.yaml, api/v1beta1/clusterresoure.go, charts/capsule-proxy/crds/capsule.clastix.io_globalproxysettings.yaml, charts/capsule-proxy/crds/capsule.clastix.io_proxysettings.yaml, e2e/global_settings_test.go, e2e/namespace_test.go, e2e/suite_test.go, e2e/utils_test.go, internal/modules/clusterscoped/get.go, internal/modules/clusterscoped/list.go, internal/modules/utils/clusterscope.go, internal/webserver/webserver.go
This PR improves the functionality of the GlobalProxySettings. The following changes are made:
1. If the flag is enabled, all routes, except namespaces and tenants, are handled by the new generic clusterScoped route. (Reported #668)
2. As filled in #681 we have a problem with request-type "smuggling". The PR already fixed it. With this PR i am dropping the operations field all together, as there will be **never** the use-case to handle any other operations than read operations. Other operations should directly hit the Kubernetes, not be rejected.
=> feat(controller): drop most legacy routes when ProxyClusterScoped is active

internal/webserver/webserver.go
Set loglevel of the token to debug (10) so it doesn't get shown in stdout log by default (4)
=> chore: set loglevel of token to debug

internal/tenant/proxytenant.go
Fixes a bug where only the last entry of multiple subjects in rules of a GlobalProxySettings was displayed to a capsule tenant owner.
Multiple **GlobalProxySettings** - works:
```
apiVersion: capsule.clastix.io/v1beta1
kind: GlobalProxySettings
metadata:
name: crd-foo
spec:
rules:
- clusterResources:
- apiGroups:
- apiextensions.k8s.io/v1
operations:
- List
resources:
- customresourcedefinitions
selector:
matchExpressions:
- key: app
operator: In
values:
- foo
subjects:
- kind: User
name: foo@example.com
---
apiVersion: capsule.clastix.io/v1beta1
kind: GlobalProxySettings
metadata:
name: crd-bar
spec:
rules:
- clusterResources:
- apiGroups:
- apiextensions.k8s.io/v1
operations:
- List
resources:
- customresourcedefinitions
selector:
matchExpressions:
- key: app
operator: In
values:
- bar …
```
=> fix(GlobalProxySettings): allow multiple subjects in rules
