- internal/webserver/webserver.go
Fixes #30. @prometherion please review.
> add namesapces lookup by groups

- internal/webserver/webserver.go
@prometherion, modified labelSelector check to fix #32. Please review.
> modified labelSelector check

- internal/request/http.go
- internal/request/request.go
- internal/webserver/webserver.go
> support for /api/v1/nodes filtering

- Dockerfile
- deploy/sidecar-setup.yaml
- deploy/standalone-setup.yaml
- go.mod
- internal/webserver/webserver.go
- main.go
> Missing renaming on code base

- .github/workflows/helm.yaml
- charts/capsule-proxy/.helmignore
- charts/capsule-proxy/Chart.yaml
- charts/capsule-proxy/README.MD
- charts/capsule-proxy/templates/NOTES.txt
- charts/capsule-proxy/templates/_helpers.tpl
- charts/capsule-proxy/templates/deployment.yaml
- charts/capsule-proxy/templates/hpa.yaml
- charts/capsule-proxy/templates/ingress.yaml
- charts/capsule-proxy/templates/post-install-job.yaml
- charts/capsule-proxy/templates/rbac.yaml
- charts/capsule-proxy/templates/service.yaml
- charts/capsule-proxy/templates/serviceaccount.yaml
- charts/capsule-proxy/values.yaml
Closes #39 
Please note, that this PR uses `/capsule-proxy` as the application name in `deployment`, so after merging it, we had to rename project and update `Dockerfile`
> Adding Helm Chart

- charts/capsule-proxy/Chart.yaml
- charts/capsule-proxy/README.md
- charts/capsule-proxy/templates/deployment.yaml
- charts/capsule-proxy/templates/ingress.yaml
- charts/capsule-proxy/templates/post-install-job.yaml
- charts/capsule-proxy/templates/service.yaml
- charts/capsule-proxy/values.yaml
> Include multiple service options for exposing the proxy in Helm Chart and fix ssl self-signed generation

- go.mod
- go.sum
- internal/webserver/webserver.go
The PR has been created for changing the library for HTTP requests.
The work has been made in pair programming with @ludusrusso!
Thx @prometherion for your help! 
Closes #54
> Move from http library to Gorilla Mux

- e2e/libs/poll.bash
- e2e/tests/00_namespaces_list.bats
- e2e/tests/01_namespaces_filtering.bats
- e2e/tests/02_node_listing.bats
Partially addressing #64: we faced some flakiness in the last commits, let's test on GH Actions to see if this works.
> test(e2e): implementing retry logic to avoid flakiness

- .github/workflows/e2e.yaml
- Dockerfile
- Makefile
- README.md
- charts/capsule-proxy/Chart.yaml
- charts/capsule-proxy/templates/deployment.yaml
> Support for debugging on remote Kubernetes cluster with delve

- Makefile
- e2e/run.bash
- e2e/tests/06_node_get.bats
- internal/request/http.go
- internal/request/request.go
- internal/webserver/nodes.go
- internal/webserver/webserver.go
Closes #40 and allows to retrieve the single Node as well labeling it.
> Read and Update on Node resource

- .github/workflows/ci.yaml
- .golangci.yml
- internal/options/http.go
- internal/options/kube.go
- internal/options/listener.go
- internal/options/server.go
- internal/request/http.go
- internal/webserver/nodes.go
- internal/webserver/webserver.go
- main.go
> golangci-linter during CI

- go.mod
- go.sum
- internal/webserver/nodes.go
- internal/webserver/panic.go
- internal/webserver/storageclass.go
- internal/webserver/webserver.go
> refactor: supporting panic with kubectl error formatting

- README.md
- e2e/libs/storageclass_utils.bash
- e2e/tests/07_storageclass.bats
- internal/webserver/storageclass.go
- internal/webserver/webserver.go
> Retrieval of StorageClass resources assigned to a Tenant

- .golangci.yml
- README.md
- e2e/libs/ingressclass_utils.bash
- e2e/tests/08_ingressclass.bats
- internal/webserver/ingressclass.go
- internal/webserver/webserver.go
> Support for IngressClass resources

- e2e/tests/07_storageclass.bats
- e2e/tests/08_ingressclass.bats
- internal/webserver/ingressclass.go
- internal/webserver/panic.go
- internal/webserver/storageclass.go
> fix: do not allow tenant owner to get ingress/storage classes not assigned

- Makefile
- e2e/kind.yaml
- e2e/tests/02_node_listing.bats
- e2e/tests/06_node_get.bats
- internal/webserver/nodes.go
> chore: node listing should rely on tenant's nodeSelector spec

- e2e/tests/07_storageclass.bats
- e2e/tests/08_ingressclass.bats
- internal/webserver/ingressclass.go
- internal/webserver/nodes.go
- internal/webserver/storageclass.go
> fix: tenant owner can delete ingress\storage classes only if tenant had annotations

- internal/request/http.go
- internal/webserver/ingressclass.go
- internal/webserver/nodes.go
- internal/webserver/storageclass.go
- internal/webserver/webserver.go
> feat: support for webhook token authentication strategy

- internal/webserver/webserver.go
> fix: incorrect handling of PATCH\PUT operations for /api/v1/namespaces

- README.md
- internal/webserver/webserver.go
Closes #88.
Plus, minor fixes on the README.md file
> Documenting new Storage and Ingress class endpoints

- internal/options/kube.go
- main.go
> refactor!: remove k8s-control-plane-url CLI flag

- internal/modules/ingressclass/utils.go
- internal/modules/node/utils.go
- internal/modules/storageclass/utils.go
- internal/modules/utils/utils.go.go
> Requiring listing annotation for deletion

- charts/capsule-proxy/Chart.yaml
- charts/capsule-proxy/templates/daemonset.yaml
- charts/capsule-proxy/templates/deployment.yaml
- deploy/sidecar-setup.yaml
- deploy/standalone-setup.yaml
> refactor!: remove --k8s-control-plane-url CLI flag from Helm Chart

- deploy/sidecar-setup.yaml
- deploy/standalone-setup.yaml
> switch from command to args

- internal/webserver/webserver.go
> bug: validateCapsuleLabel should get tenants not only for user, but also for groups

- charts/capsule-proxy/README.md
- charts/capsule-proxy/templates/daemonset.yaml
- charts/capsule-proxy/templates/deployment.yaml
- charts/capsule-proxy/values.yaml
- go.mod
- internal/options/kube.go
- internal/options/listener.go
- internal/webserver/middleware/user_in_group.go
- internal/webserver/webserver.go
- main.go
> enable multiple values for capsule-user-group

- .github/workflows/e2e.yaml
- Makefile
- README.md
- e2e/run.bash
- e2e/tests/metrics/get.bats
- e2e/tests/metrics/list.bats
- go.sum
- internal/modules/metric/get.go
- internal/modules/metric/list.go
- internal/modules/utils/node.go
- internal/webserver/webserver.go
This PR resolves #114 
It will allow to access node metrics using the same approach of accessing nodes. In order to simplify some code, the file `utils.go` has been moved to a new package in order to be shared between several packages, in this case `node` and `metric`.
> Owner can read node metrics

- README.md
Including metrics url and also sorting them
> docs: including metrics url

- charts/capsule-proxy/Chart.yaml
> build(helm): update chart version to 0.1.5 and app version to 0.1.1

- .github/workflows/docker-ci.yaml
- .github/workflows/e2e.yaml
- Dockerfile
> add ci to create docker images for amd/arm architectures

- charts/capsule-proxy/templates/NOTES.txt
A space was missing in Helm NOTES.txt
> fix: just a space in helm NOTES.txt

- Makefile
- e2e/libs/rolebinding_utils.bash
- e2e/tests/namespaces/list.bats
- go.mod
- go.sum
- internal/controllers/role_bindings.go
- internal/modules/ingressclass/get.go
- internal/modules/ingressclass/list.go
- internal/modules/lease/get.go
- internal/modules/metric/get.go
- internal/modules/metric/list.go
- internal/modules/module.go
- internal/modules/namespace/list.go
- internal/modules/node/get.go
- internal/modules/node/list.go
- internal/modules/pod/get.go
- internal/modules/priorityclass/get.go
- internal/modules/priorityclass/list.go
- internal/modules/storageclass/get.go
- internal/modules/storageclass/list.go
- internal/request/http.go
- internal/request/request.go
- internal/webserver/webserver.go
- main.go
> regular users should be able to get namespace list

- README.md
- go.mod
- go.sum
- internal/request/http.go
> golang-jwt/jwt as new jwt library

- internal/controllers/role_bindings.go
> fix: rolebindings reflector must restart watch in case of connection problems

- charts/capsule-proxy/templates/ingress.yaml
> build(helm): ingress support for kubernetes >= 1.22

- charts/capsule-proxy/README.md
> docs: more context for rolebindings sync period flag

- e2e/kubectl-https-tests/ingressclasses/delete.bats
- e2e/kubectl-https-tests/ingressclasses/get.bats
- e2e/kubectl-https-tests/ingressclasses/list.bats
- e2e/kubectl-https-tests/ingressclasses/update.bats
- e2e/libs/proxysetting_utils.bash
Adds tests for https://github.com/clastix/capsule-proxy/issues/197
> chore(tests): add tests for proxysettings custom resource

- charts/capsule-proxy/Chart.yaml
- charts/capsule-proxy/README.md
- charts/capsule-proxy/values.yaml
> build(helm): change default for ServiceMonitor

- charts/capsule-proxy/Chart.yaml
- charts/capsule-proxy/README.md
- charts/capsule-proxy/values.yaml
> build(helm): change default for generateCertificates

- .github/workflows/ci.yaml
- .golangci.yml
- Dockerfile
- go.mod
- go.sum
> Go 1.18 support

- Makefile
- internal/modules/namespace/get.go
- internal/webserver/webserver.go
> feat: support for owned namespace retrieval

- internal/request/http.go
Signed-off-by: Massimiliano Giovagnoli <me@maxgio.it>
> feat(internal/request/http.go): check impersonation also of groups

- Makefile
- e2e/kubectl-https-tests/namespaces/list.bats
- e2e/run.bash
- internal/request/error.go
- internal/request/http.go
- internal/webserver/webserver.go
> Support for user impersonation

- charts/capsule-proxy/Chart.yaml
- charts/capsule-proxy/templates/_helpers.tpl
- charts/capsule-proxy/templates/certmanager.yaml
- charts/capsule-proxy/values.yaml
fixes: #213
Signed-off-by: Vivek Singh <svivekkumar@vmware.com>
> feat: use cert-manager for SSL certificates

- internal/webserver/webserver.go
> disable metrics middleware

- internal/modules/ingressclass/list.go
- internal/modules/metric/list.go
- internal/modules/namespace/list.go
- internal/modules/node/list.go
- internal/modules/priorityclass/list.go
- internal/modules/storageclass/list.go
- internal/webserver/webserver.go
> bug: incorrect handling of trailing slashes in list requests

- internal/modules/namespace/const.go
- internal/modules/namespace/list.go
- internal/modules/namespace/post.go
- internal/webserver/webserver.go
> fix: namespace creationg handler with user impersonation

- internal/modules/ingressclass/get.go
- internal/modules/ingressclass/list.go
- internal/modules/ingressclass/utils.go
- internal/modules/priorityclass/get.go
- internal/modules/priorityclass/list.go
- internal/modules/priorityclass/utils.go
- internal/modules/storageclass/get.go
- internal/modules/storageclass/list.go
- internal/modules/storageclass/utils.go
> fix: user with list permissions shouldn't be able to create objects

- internal/modules/ingressclass/list.go
- internal/modules/metric/list.go
- internal/modules/namespace/const.go
- internal/modules/node/list.go
- internal/modules/priorityclass/list.go
- internal/modules/storageclass/list.go
> fix: unable to list nodes as a tenant owner (#254)

- .github/workflows/e2e.yaml
- Makefile
- internal/request/http.go
Fix was successfully tested with this change. Now the question remains if the change is breaking. IMHO it is not but we can still talk about that.
FYI: i think the e2e is a bit broken. I will also try to fix it :)
closes #245
> feat: defer impersonation user assignment

- .github/workflows/e2e.yaml
- Makefile
> fix(test): metrics-server chart bump up to v6.2.9

- internal/request/http.go
- internal/request/http_test.go
- internal/request/impersonation.go
- internal/webserver/middleware/allowed_requests.go
- internal/webserver/middleware/user_in_group.go
- internal/webserver/webserver.go
> Sanitizing user impersionation handlers

- internal/request/http.go
> fix: fallback to multiple auth strategies

- charts/capsule-proxy/README.md
- charts/capsule-proxy/templates/_helpers.tpl
- charts/capsule-proxy/templates/certgen-job.yaml
- charts/capsule-proxy/values.yaml
> chore(helm): support for self-signed SANs

- internal/controllers/capsule_configuration.go
- main.go
Closes #292.
@latchmihay may I ask you for a review?
> fix: ensure capsuleconfiguration exists at startup

- main.go
> feat: add client side rate limiters

- internal/modules/errors/bad_request.go
- internal/modules/errors/not_allowed.go
- internal/modules/errors/not_found.go
- internal/modules/ingressclass/get.go
- internal/modules/ingressclass/list.go
- internal/modules/metric/get.go
- internal/modules/metric/list.go
- internal/modules/namespace/get.go
- internal/modules/namespace/list.go
- internal/modules/node/get.go
- internal/modules/node/list.go
- internal/modules/persistentvolume/get.go
- internal/modules/persistentvolume/list.go
- internal/modules/pod/get.go
- internal/modules/priorityclass/get.go
- internal/modules/priorityclass/list.go
- internal/modules/runtimeclass/get.go
- internal/modules/runtimeclass/list.go
- internal/modules/storageclass/get.go
- internal/modules/storageclass/list.go
- internal/modules/utils/selector.go
> Fixing proxying for tenant owners owning multiple tenants

- charts/capsule-proxy/Chart.yaml
- charts/capsule-proxy/README.md
- charts/capsule-proxy/values.yaml
> fix(helm): removing unused options.k8sControlPlaneUrl value

- .github/maintainers.yaml
- README.md
This should bring CLO monitoring for capsule-proxy to 100
> chore(repo): add maintainers.yaml

- .github/maintainers.yaml
- .github/workflows/docker-publish.yml
- .github/workflows/helm-publish.yml
> chore(ci): move to new organisation

- .github/workflows/docker-publish.yml
- .github/workflows/helm-test.yml
- Makefile
> fix(ci): image publish flow

- charts/capsule-proxy/Chart.yaml
- charts/capsule-proxy/README.md
- charts/capsule-proxy/templates/_helpers.tpl
- charts/capsule-proxy/values.yaml
> chore(helm): prepare v0.4.5

- charts/capsule-proxy/Chart.yaml
> chore(helm): releasing v0.5.1

- charts/capsule-proxy/Chart.yaml
> chore(helm): releaseing v0.5.2

- charts/capsule-proxy/Chart.yaml
> chore(helm): relesing v0.5.3

- .github/maintainers.yaml
Related to https://github.com/projectcapsule/capsule/issues/962
> chore(.github/maintainers.yaml): add maxgio92 as new maintainer

- Makefile
- charts/capsule-proxy/README.md
- charts/capsule-proxy/ci/ds-values.yaml
- charts/capsule-proxy/templates/certgen-job.yaml
- charts/capsule-proxy/templates/certmanager.yaml
- charts/capsule-proxy/values.yaml
> feat: add scheduling values

- .github/workflows/helm-publish.yml
- .goreleaser.yml
Release Helm chart with controller image release (coupled versioning)
> feat(ci): align helm release with controller release

- charts/capsule-proxy/README.md
- charts/capsule-proxy/README.md.gotmpl
Change helm repo url to the correct repo.
> fix(docs): change capsule helm repo url

- internal/controllers/watchdog/utils.go
> fix: skipping non watchable resources

- .github/workflows/releaser.yml
> chore: fix goreleaser

- charts/capsule-proxy/README.md
- charts/capsule-proxy/ci/deploy-values.yaml
- charts/capsule-proxy/templates/NOTES.txt
- charts/capsule-proxy/templates/certmanager.yaml
- charts/capsule-proxy/templates/hpa.yaml
- charts/capsule-proxy/templates/ingress.yaml
- charts/capsule-proxy/templates/metrics-rbac.yaml
- charts/capsule-proxy/templates/rbac.yaml
- charts/capsule-proxy/values.yaml
adds some quality of life improvements to the helm chart
> feat(chart): add autoscaling values

- charts/capsule-proxy/Chart.yaml
> chore(artifacthub): changes for v0.8.0 release

- internal/controllers/watchdog/namespaced_watcher.go
This is necessary when a Tenant has multiple Ownerreferences, this check verifies if one of the ownerreferences is a capsule reference.
> fix(controller): inspect all references

- .github/workflows/stale.yml
- charts/capsule-proxy/templates/crd-lifecycle/job.yaml
> chore: add stale-workflow & fix helm

- charts/capsule-proxy/templates/certgen-job.yaml
> chore: fix helm

- main.go
> fix(controller): add leader-election

- charts/capsule-proxy/README.md
- charts/capsule-proxy/values.schema.json
- charts/capsule-proxy/values.yaml
- main.go
> feat(controller): add flag for rbac reflector
